endpoint = 127.0.0.1:3000

POST 
<endpoint>/signup
Basic auth: false
Session: false

POST
<endpoint>/login
Basic auth: true
Session: false
RET
session: plain/text


GET
<endpoint>/news
Basic auth: false
Session: true
RET
news[]: json

POST
<endpoint>/news
Basic auth: false
Session: true